artifact_uri: file:///home/vboxuser/Compagnon_new/Compagnon_immo_25/mlruns/66a33dcd119e40d0874bb74fc5735b19/artifacts
end_time: 1760748771934
entry_point_name: ''
experiment_id: '590107318283490497'
lifecycle_stage: active
run_id: 66a33dcd119e40d0874bb74fc5735b19
run_name: Import incrémental [s3]
source_name: ''
source_type: 4
source_version: ''
start_time: 1760748157803
status: 4
tags: []
user_id: vboxuser
