name: MLflow smoke
on: [workflow_dispatch, push]
jobs:
  test-mlflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.10' }
      - name: Validate dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow python-dotenv
      - name: MLflow log to DagsHub
        env:
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
        run: |
          python - <<'PY'
          import os, mlflow
          os.environ["MLFLOW_TRACKING_USERNAME"] = os.environ["DAGSHUB_USER"]
          os.environ["MLFLOW_TRACKING_PASSWORD"] = os.environ["DAGSHUB_TOKEN"]
          mlflow.set_tracking_uri(os.environ["MLFLOW_TRACKING_URI"])
          mlflow.set_experiment("ci-smoke")
          with mlflow.start_run(run_name="gha"):
              mlflow.log_param("runner","gha")
              mlflow.log_metric("ci_ping", 1)
          print("Logged to:", mlflow.get_tracking_uri())
          PY

