artifact_uri: file:///home/vboxuser/Compagnon_new/Compagnon_immo_25/mlruns/0e9d97342eb44cdba024ca369e3fed3b/artifacts
end_time: 1760744716543
entry_point_name: ''
experiment_id: '590107318283490497'
lifecycle_stage: active
run_id: 0e9d97342eb44cdba024ca369e3fed3b
run_name: Import incrémental [s3]
source_name: ''
source_type: 4
source_version: ''
start_time: 1760744686528
status: 4
tags: []
user_id: vboxuser
