# Dockerfile
FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

WORKDIR /app

# (Optionnel) build deps si besoin de wheels natifs
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Dépendances
COPY requirements.txt /app/mlops/0_config/requirements.txt
RUN pip install -r requirements.txt

# Code
COPY . .

# Utilisateur non-root
RUN useradd -m appuser && chown -R appuser /app
USER appuser


COPY entrypoint.sh /app/mlops/0_config/entrypoint.sh
RUN chmod +x entrypoint.sh

CMD ["python", "-c", "import mlflow_connect as m; m.configure_mlflow(); import train_example as t; t.main()"]
