version: '3.8'

services:
  encode:
    build:
      context: .
      dockerfile: Dockerfile.encoding
    volumes:
      - ./mlops:/app/mlops

  train_lgbm:
    build:
      context: .
      dockerfile: Dockerfile.lgbm
    volumes:
      - ./mlops:/app/mlops

  train_xgb:
    build:
      context: .
      dockerfile: Dockerfile.xgb
    volumes:
      - ./mlops:/app/mlops

  analyse:
    build:
      context: .
      dockerfile: Dockerfile.analyse
    volumes:
      - ./mlops:/app/mlops
