FROM python:3.10-slim


# 1. Dépendances système
RUN apt-get update && apt-get install -y git dvc && apt-get clean

# 2. Dossier de travail
WORKDIR /app

# 3. Copie du script et des sources
COPY . .
# 4. Droits d’exécution du script
RUN chmod +x /app/run_dvc.sh
# 5. Commande par défaut
CMD ["./run_dvc.sh"]

