# Dockerfile.dvc

FROM compagnon_immo-run

WORKDIR /app

# Dépendances système minimales
RUN apt-get update && apt-get install -y \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copie complète du projet
COPY . .

# Activation DVC si besoin
CMD ["bash"]
s
