version: '3.8'

services:
  # --------- Partie Régression ----------
  encode:
    build:
      context: .
      dockerfile: Dockerfile.encoding.REG
    volumes:
      - ./mlops:/app/mlops

  train_lgbm:
    build:
      context: .
      dockerfile: Dockerfile.lgbm.REG
    volumes:
      - ./mlops:/app/mlops

  train_xgb:
    build:
      context: .
      dockerfile: Dockerfile.xgb.REG
    volumes:
      - ./mlops:/app/mlops

  analyse:
    build:
      context: .
      dockerfile: Dockerfile.analyse.REG
    volumes:
      - ./mlops:/app/mlops

  # --------- Partie Séries Temporelles ----------
  split:
    build:
      context: .
      dockerfile: Dockerfile.split.ST
    volumes:
      - ./data:/app/data
      - ./exports:/app/exports
    command: >
      --input-path /app/data/df_sales_clean_ST.csv --output-folder /app/exports/st

  decompose:
    build:
      context: .
      dockerfile: Dockerfile.decompose.ST
    volumes:
      - ./exports:/app/exports
    command: >
      --input-folder /app/exports/st --output-folder /app/exports/st

  train_sarimax:
    build:
      context: .
      dockerfile: Dockerfile.sarimax.ST
    volumes:
      - ./exports:/app/exports
    command: >
      --input-folder /app/exports/st --output-folder /app/exports/st

  evaluate:
    build:
      context: .
      dockerfile: Dockerfile.evaluate.ST
    volumes:
      - ./exports:/app/exports
    command: >
      --model-folder /app/exports/st

  # --------- Tracking Expériences ----------
  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./mlruns --host 0.0.0.0

  # --------- Services Factices pour scripts ----------
  regression_script:
    image: busybox
    command: echo "Présence logique de regression/run_all.sh"

  st_script:
    image: busybox
    command: echo "Présence logique de Serie_temporelle/run_all_st.sh"

  # --------- Exécution du pipeline complet ----------
  run_full:
    build:
      context: .
      dockerfile: Dockerfile.run
    volumes:
      - .:/home/mlopsuser/app
    depends_on:
      - regression_script
      - st_script
    tty: true
    stdin_open: true
    environment:
      - RUN_MODE=full

