# Dockerfile.encoding.REG
FROM python:3.10-slim

WORKDIR /app

COPY ./mlops/Regression /app/mlops
COPY ./data /app/data
COPY ./exports /app/exports

RUN pip install -r /app/mlops/requirements.txt

CMD ["python", "/app/mlops/encoding.py"]

