FROM python:3.10-lgbm
WORKDIR /app

COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

ENTRYPOINT ["python", "./mlops/Regression/utils.py"]
ENTRYPOINT ["uvicorn", "utils_api:app", "--host", "0.0.0.0", "--port", "8009"]



