FROM compagnon_immo-clust

WORKDIR /app

COPY ./mlops/Regression /app/mlops
COPY ./data /app/data
COPY ./exports /app/exports


ENTRYPOINT ["uvicorn", "encoding_api:app", "--host", "0.0.0.0", "--port", "8003"]

