# docker-compose.yml — Compagnon Immo (version corrigée)
# - Aligne chemins Dockerfile/scripts avec le Makefile
# - Fixe MLflow (backend + artifact root) et healthcheck
# - Uniformise mounts, users, networks, depends_on (service_healthy)
# - Ajoute des profiles (regression, series) pour cibler les runs

services:
  # --------- Tracking MLflow ----------
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: compagnon_immo-mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow
    command: >-
      mlflow server
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow
      --host 0.0.0.0
      --port 5000
    networks:
      - ml_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --------- Pipeline de lancement ----------
  run_full:
    build:
      context: .
      dockerfile: mlops/1_import_donnees/Dockerfile.run
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    environment:
      - RUN_MODE=full
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net

  # --------- Préparation des données ----------
  fusion_geo:
    build:
      context: .
      dockerfile: mlops/3_fusion/Dockerfile.fusion
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
      - ./mlops:/app/mlops
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    command: ["bash", "-lc", "python mlops/3_fusion/fusion.py"]
    profiles: ["regression", "series"]

  preprocessing:
    build:
      context: .
      dockerfile: mlops/preprocessing_4/Dockerfile.preprocessing
    image: compagnon_immo-preprocessing
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./mlops/preprocessing_4:/app/mlops/preprocessing_4
    command: >-
      python mlops/preprocessing_4/preprocessing.py
      --input-path /app/data
      --output-folder1 /app/data
      --output-folder2 /app/data
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    profiles: ["regression", "series"]

  clustering:
    build:
      context: .
      dockerfile: mlops/5_clustering/Dockerfile.clustering
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/app/data
      - ./mlops:/app/mlops
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    command: >-
      python mlops/5_clustering/Clustering.py
      --input-path /app/data/train_clean.csv
      --output-path1 /app/data/df_cluster.csv
      --output-path2 /app/data/df_sales_clean_ST.csv
    profiles: ["regression", "series"]

  encode:
    build:
      context: .
      dockerfile: mlops/6_Regression/1_Encoding/Dockerfile.encoding.REG
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./mlops/6_Regression/1_Encoding:/app/mlops/6_Regression/1_Encoding
      - ./data:/app/data
      - ./exports:/app/exports
    command: ["python", "/app/mlops/6_Regression/1_Encoding/encoding.py"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    profiles: ["regression"]

  # --------- Régression ----------
  train_lgbm:
    build:
      context: .
      dockerfile: mlops/6_Regression/2_LGBM/Dockerfile.lgbm.REG
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./mlops/6_Regression/2_LGBM:/app/mlops/6_Regression/2_LGBM
      - ./data:/app/data
      - ./exports:/app/exports
    command: ["python", "/app/mlops/6_Regression/2_LGBM/train_lgbm.py"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    profiles: ["regression"]

  analyse:
    build:
      context: .
      dockerfile: mlops/6_Regression/4_Analyse/Dockerfile.analyse.REG
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./mlops/6_Regression/4_Analyse:/app/mlops/6_Regression/4_Analyse
      - ./exports:/app/exports
      - ./data:/app/data
    command: ["python", "/app/mlops/6_Regression/4_Analyse/analyse.py"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    profiles: ["regression"]

  # --------- Séries Temporelles ----------
  split:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/1_SPLIT/Dockerfile.split.ST
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./exports:/app/exports
      - ./data:/app/data
      - ./mlops:/app/mlops
    entrypoint: ["python", "/app/mlops/7_Serie_temporelle/1_SPLIT/load_split.py"]
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - RUN_MODE=full
      - ST_SUFFIX=${ST_SUFFIX:-q12}
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    profiles: ["series"]

  decompose:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/2_Decompose/Dockerfile.decompose.ST
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./exports:/app/exports
      - ./mlops:/app/mlops
    command: >-
      python /app/mlops/7_Serie_temporelle/2_Decompose/seasonal_decomp.py
      --input-folder /app/exports/st
      --output-folder /app/exports/st
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
      - RUN_MODE=full
      - ST_SUFFIX=${ST_SUFFIX:-q12}
    depends_on:
      mlflow:
        condition: service_healthy
    networks:
      - ml_net
    profiles: ["series"]

  train_sarimax:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/3_SARIMAX/Dockerfile.sarimax.ST
    user: "${UID:-1000}:${GID
