FROM compagnon_immo-util
WORKDIR /app

COPY mlops/Regression /app/mlops 
COPY exports /app/exports
COPY services /app

EXPOSE 8005
ENTRYPOINT ["uvicorn", "analyse_api:app", "--host", "0.0.0.0", "--port", "8005"]
