services:
  # Base de données PostgreSQL pour Airflow
  postgres-airflow:
    image: postgres:16
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ml_net
    profiles: ["airflow"]

  # Redis pour les tâches en arrière-plan
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # Port hôte changé pour éviter le conflit
    networks:
      - ml_net

  # MLflow pour le suivi des expériences
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.13.1
    ports:
      - "5050:5050"
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5050
      --backend-store-uri sqlite:///mlflow.db
      --default-artifact-root /mlflow/artifacts
    volumes:
      - mlflow_artifacts:/mlflow/artifacts
    networks:
      - ml_net

  # Airflow Webserver
  airflow-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "
        airflow db upgrade &&
        airflow webserver --port 8081
      "
    ports:
      - "8081:8081"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW_UID: 50000
      MLFLOW_TRACKING_URI: http://mlflow:5050
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - .:/opt/airflow/repo
      - ./data:/opt/airflow/data
      - ./exports:/opt/airflow/exports
      - ./mlops:/opt/airflow/mlops
    depends_on:
      - postgres-airflow
      - redis
      - mlflow
    networks:
      - ml_net
    profiles: ["airflow"]

  # Airflow Scheduler
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    command: airflow scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow/airflow
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW_UID: 50000
      MLFLOW_TRACKING_URI: http://mlflow:5050
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - .:/opt/airflow/repo
      - ./data:/opt/airflow/data
      - ./exports:/opt/airflow/exports
      - ./mlops:/opt/airflow/mlops
    depends_on:
      - postgres-airflow
      - redis
      - mlflow
    networks:
      - ml_net
    profiles: ["airflow"]

  # API FastAPI
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5050
    depends_on:
      - mlflow
      - redis
    networks:
      - ml_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Service DVC pour les pipelines de données
  dvc:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - .:/app
      - ./data:/app/data
      - ./exports:/app/exports
    working_dir: /app
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5050
      - DVC_NO_ANALYTICS=1
    depends_on:
      - mlflow
    networks:
      - ml_net
    profiles: ["dvc"]

  # Service de test automatisé
  api-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - API_BASE_URL=http://api:8000/api/v1
      - MLFLOW_TRACKING_URI=http://mlflow:5050
      - PYTHONPATH=/app
    depends_on:
      api:
        condition: service_healthy
      mlflow:
        condition: service_started
    networks:
      - ml_net
    command: python -m pytest app/api/tests -v
    profiles: ["test"]

# Définir les volumes une seule fois à la racine
volumes:
  postgres_data:
  mlflow_artifacts:

# Définir les networks une seule fois à la racine
networks:
  ml_net:
    driver: bridge

