FROM python:3.10-slim

# creation dossier
WORKDIR /app

COPY requirements.txt .
COPY mlops/fusion ./mlops/fusion
COPY data /app/data

RUN pip install --no-cache-dir -r requirements.txt

# import data
RUN dvc pull

ENTRYPOINT ["python", "mlops/fusion/fusion_geo_dvf.py"]
