FROM compagnon_immo-lgbm
WORKDIR /app

COPY requirements.txt .
#RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

EXPOSE 8009

ENTRYPOINT ["uvicorn", "utils_api:app", "--host", "0.0.0.0", "--port", "8009"]



