FROM compagnon_immo-clust

WORKDIR /app

COPY ./mlops/Regression /app/mlops
COPY services /app
COPY ./data /app/data
COPY ./exports /app/exports

EXPOSE 8003

ENTRYPOINT ["uvicorn", "encoding_api:app", "--host", "0.0.0.0", "--port", "8003"]

