FROM compagnon_immo-encod
WORKDIR /app


COPY mlops/Regression /app/mlops 
COPY exports /app/exports
COPY api_rest /app

ENTRYPOINT ["uvicorn", "train_lgbm_api:app", "--host", "0.0.0.0", "--port", "8004"]

