# ------------------------------------------------------------
# Airflow + Postgres minimal, fiable et prêt à l’emploi
# - Web UI: http://localhost:8080
# - DB: Postgres 15
# - Healthchecks + depends_on (service_healthy)
# - Variables sensibles via .env (AIRFLOW__*, etc.)
# ------------------------------------------------------------

x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.9.2}
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR:-LocalExecutor}
    AIRFLOW__CORE__DEFAULT_TIMEZONE: ${AIRFLOW__CORE__DEFAULT_TIMEZONE:-Europe/Paris}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES:-false}
    AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW__WEBSERVER__SECRET_KEY}
    MLFLOW_S3_ENDPOINT_URL: ${AWS_ENDPOINT_URL_S3}
    AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
    _PIP_ADDITIONAL_REQUIREMENTS: >
      mlflow==2.15.1
      scikit-learn==1.4.2
      dvc[s3]==3.50.1
      lightgbm==4.5.0
      xgboost==2.1.1
      category-encoders==2.6.3
      shap==0.46.0
      boto3==1.34.146

  volumes:
    - .:/opt/airflow/repo
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./exports:/opt/airflow/exports
  user: "${AIRFLOW_UID:-1000}:0"
  networks:
    - ml_net



services:
  postgres-airflow:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow -d airflow -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks: [ml_net]
    ports: ["5432:5432"]  # optionnel

  airflow-init:
    <<: *airflow-common
    image: airflow-ml:latest     # nom de l'image produite par build
    build:
      context: .
      dockerfile: dags/Dockerfile.airflow
    user: "${AIRFLOW_UID:-1000}:0"
    command: ["bash","-lc","airflow db upgrade && airflow users create --role Admin --username ${AIRFLOW_ADMIN_USERNAME:-admin} --password ${AIRFLOW_ADMIN_PASSWORD:-admin} --firstname Admin --lastname User --email ${AIRFLOW_ADMIN_EMAIL:-admin@example.com} || true"]
    depends_on:
      postgres-airflow:
        condition: service_healthy
    networks: [ml_net]

    

  airflow-webserver:
    image: apache/airflow:2.9.2
    user: "${AIRFLOW_UID:-1000}:0"
    env_file: [.env]
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
    command: ["webserver"]
    ports: ["8080:8080"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./exports:/opt/airflow/exports
      - .:/opt/airflow/repo
    depends_on:
      postgres-airflow:
        condition: service_healthy
    networks: [ml_net]


  airflow-scheduler:
    image: apache/airflow:2.9.2
    user: "${AIRFLOW_UID:-1000}:0"
    env_file: [.env]
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags
      _PIP_ADDITIONAL_REQUIREMENTS: >
        mlflow==2.15.1 scikit-learn==1.4.2 dvc[s3]==3.50.1 lightgbm==4.5.0
        xgboost==2.1.1 category-encoders==2.6.3 shap==0.46.0 boto3==1.34.146
    command: ["scheduler"]
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./exports:/opt/airflow/exports
      - .:/opt/airflow/repo
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    networks: [ml_net]


  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: ["8000:8000"]
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
    networks: [ml_net]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  dvc:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./exports:/app/exports
    working_dir: /app
    environment:
      MLFLOW_TRACKING_URI: ${MLFLOW_TRACKING_URI}
      MLFLOW_TRACKING_USERNAME: ${MLFLOW_TRACKING_USERNAME}
      MLFLOW_TRACKING_PASSWORD: ${MLFLOW_TRACKING_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${REGION}
      S3_ENDPOINT: ${AWS_ENDPOINT_URL_S3}
    networks: [ml_net]
    profiles: ["dvc"]

  api-test:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    volumes:
      - ./app:/app/app
      - ./params.yaml:/app/params.yaml
      - ./app/api/tests:/app/app/api/tests
    working_dir: /app
    environment:
      - API_BASE_URL=http://api:8000/api/v1
    depends_on:
      api:
        condition: service_healthy
    networks: [ml_net]
    command: bash -c "cd /app && ls -la app/api/tests && python -m pytest app/api/tests -v"
    profiles: ["test", "regression", "series"]

  ci:
    build:
      context: .
      dockerfile: Dockerfile
    user: "${UID:-1000}:${GID:-1000}"
    volumes: [".:/app"]
    working_dir: /app
    environment: ["PYTHONPATH=/app"]
    networks: [ml_net]
    command: >
      bash -c "python -m pytest app/api/tests -v &&
               python -m flake8 app/ --max-line-length=88 --ignore=E203,W503"
    profiles: ["ci"]

  prometheus:
    image: prom/prometheus:v2.45.0
    ports: ["9090:9090"]
    volumes:
      - ./infra/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks: [ml_net]
    profiles: ["monitoring"]

  grafana:
    image: grafana/grafana:10.1.0
    ports: ["3000:3000"]
    volumes:
      - ./infra/monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./infra/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      prometheus:
        condition: service_started
    networks: [ml_net]
    profiles: ["monitoring"]

  run_full:
    build:
      context: .
      dockerfile: mlops/1_import_donnees/Dockerfile.run
    user: "${UID:-1000}:${GID:-1000}"
    volumes: [".:/app"]
    tty: true
    stdin_open: true
    env_file: [.env]
    environment: ["RUN_MODE=full"]
    networks: [ml_net]


  preprocessing:
    build:
      context: .
      dockerfile: mlops/preprocessing_4/Dockerfile.preprocessing
    image: compagnon_immo_25-preprocessing
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./mlops/preprocessing_4:/app/mlops/preprocessing_4
    env_file: [.env]
    command: ["python","mlops/preprocessing_4/preprocessing.py","--input-path","/app/data","--output-path","/app/data"]
    networks: [ml_net]
    profiles: ["regression", "series"]

  clustering:
    build:
      context: .
      dockerfile: mlops/5_clustering/Dockerfile.clustering
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./data:/app/data
      - ./mlops:/app/mlops
    env_file: [.env]
    networks: [ml_net]
    command: ["python","mlops/5_clustering/Clustering.py","--input-path","/app/data/train_clean.csv","--output-path1","/app/data/df_cluster.csv","--output-path2","/app/data/df_sales_clean_ST.csv"]
    profiles: ["regression", "series"]

  encode:
    build:
      context: .
      dockerfile: mlops/6_Regression/1_Encoding/Dockerfile.encoding.REG
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./mlops/6_Regression/1_Encoding:/app/mlops/6_Regression/1_Encoding
      - ./data:/app/data
      - ./exports:/app/exports
    command: ["python", "/app/mlops/6_Regression/1_Encoding/encoding.py"]
    env_file: [.env]
    networks: [ml_net]
    profiles: ["regression"]

  train_lgbm:
    build:
      context: .
      dockerfile: mlops/6_Regression/2_LGBM/Dockerfile.lgbm.REG
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./mlops/6_Regression/2_LGBM:/app/mlops/6_Regression/2_LGBM
      - ./data:/app/data
      - ./exports:/app/exports
    command: ["python", "/app/mlops/6_Regression/2_LGBM/train_lgbm.py"]
    env_file: [.env]
    networks: [ml_net]
    profiles: ["regression"]

  analyse:
    build:
      context: .
      dockerfile: mlops/6_Regression/4_Analyse/Dockerfile.analyse.REG
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./mlops/6_Regression/4_Analyse:/app/mlops/6_Regression/4_Analyse
      - ./exports:/app/exports
      - ./data:/app/data
    command: ["python", "/app/mlops/6_Regression/4_Analyse/analyse.py"]
    env_file: [.env]
    networks: [ml_net]
    profiles: ["regression"]

  split:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/1_SPLIT/Dockerfile.split.ST
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./exports:/app/exports
      - ./data:/app/data
      - ./mlops:/app/mlops
    entrypoint: ["python", "/app/mlops/7_Serie_temporelle/1_SPLIT/load_split.py"]
    env_file: [.env]
    environment:
      - RUN_MODE=full
      - ST_SUFFIX=${ST_SUFFIX:-q12}
    networks: [ml_net]
    profiles: ["series"]

  decompose:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/2_Decompose/Dockerfile.decompose.ST
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./exports:/app/exports
      - ./mlops:/app/mlops
    command: ["python","/app/mlops/7_Serie_temporelle/2_Decompose/seasonal_decomp.py","--input-folder","/app/exports/st","--output-folder","/app/exports/st"]
    env_file: [.env]
    environment:
      - RUN_MODE=full
      - ST_SUFFIX=${ST_SUFFIX:-q12}
    networks: [ml_net]
    profiles: ["series"]

  train_sarimax:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/3_SARIMAX/Dockerfile.sarimax.ST
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./exports:/app/exports
      - ./mlops:/app/mlops
    command: ["python","/app/mlops/7_Serie_temporelle/3_SARIMAX/sarimax_api.py","--input-folder","/app/exports/st","--output-folder","/app/exports/st"]
    env_file: [.env]
    environment:
      - RUN_MODE=full
      - ST_SUFFIX=${ST_SUFFIX:-q12}
    networks: [ml_net]
    profiles: ["series"]

  evaluate:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/4_EVALUATE/Dockerfile.evaluate.ST
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./exports:/app/exports
      - ./mlops:/app/mlops
      - ./data:/app/data
    entrypoint: ["python", "/app/mlops/7_Serie_temporelle/4_EVALUATE/evaluate_ST.py"]
    env_file: [.env]
    environment:
      - RUN_MODE=full
      - ST_SUFFIX=${ST_SUFFIX:-q12}
    networks: [ml_net]
    profiles: ["series"]

  series_pipeline:
    build:
      context: .
      dockerfile: mlops/7_Serie_temporelle/Dockerfile.series_pipeline
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./mlops:/app/mlops
      - ./data:/app/data
      - ./exports:/app/exports
    command: ["python", "/app/mlops/7_Serie_temporelle/pipeline.py", "--help"]
    env_file: [.env]
    networks: [ml_net]
    profiles: ["series"]
  
  mlflow:
    image: python:3.10-slim
    container_name: compagnon_mlflow
    command: bash -lc "\
      pip install --no-cache-dir mlflow && \
      mkdir -p /opt/mlflow/artifacts && \
      mlflow server \
        --backend-store-uri sqlite:////opt/mlflow/mlflow.db \
        --default-artifact-root /opt/mlflow/artifacts \
        --host 0.0.0.0 --port 5000"
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow:/opt/mlflow
    networks: [ml_net]

volumes:
  postgres_data: 
  mlflow_artifacts:

networks:
  ml_net:
    driver: bridge
  
