# path: dvc.yaml
stages:
  import_data:
    cmd: IMP_APPEND_ONLY=1 IMP_DEDUP_DUCKDB=1 bash mlops/1_import_donnees/run_import.sh
    deps:
      - mlops/1_import_donnees/run_import.sh
      - mlops/1_import_donnees/import_data.py
    outs:
      - data/df_sample.csv
      - data/state/checkpoint.parquet
      - data/incremental
#    always_changed: true

  preprocessing:
    cmd: python -m mlops.preprocessing_4.preprocessing --input data --out-dir data/processed
    deps:
      - mlops/preprocessing_4/preprocessing.py
      - mlops/preprocessing_4/utils.py
      - data/df_sample.csv
    outs:
      - data/processed

  clustering:
    cmd: CLUSTERING_SAFE=1 python mlops/5_clustering/Clustering.py --input-path data/processed --output-path exports/df_cluster.csv
    deps:
      - mlops/5_clustering/Clustering.py
      - data/processed/df_sales_clean_train.csv
      - data/processed/df_sales_clean_test.csv        
      - data/contours-codes-postaux.geojson  # spacial
    outs:
      - exports/df_cluster.csv
      - data/df_sales_clean_ST.csv
    metrics:
      - mlflow_outputs/cluster_input.csv
    plots:
      - mlflow_outputs/elbow_plot.png

  encode:
    cmd: python mlops/6_Regression/1_Encoding/encoding.py --data-path data/df_cluster.csv --output data/encoded
    deps:
      - mlops/6_Regression/1_Encoding/encoding.py
      - exports/df_cluster.csv
    outs:
      - data/encoded
  
  train_lgbm:
    cmd: >
      python mlops/6_Regression/2_LGBM/train_lgbm.py
      && mkdir -p models
      && mv data/encoded/lgbm_model.joblib models/lgbm_model.joblib   # si ton script écrit encore là
    deps:
      - mlops/6_Regression/2_LGBM/train_lgbm.py
      - data/encoded/X_train.csv
      - data/encoded/y_train.csv
    outs:
      - models/lgbm_model.joblib
    metrics:
      - metrics/train_lgbm.json
    plots:
      - reports/feature_importance.json
    
  analyse:
    cmd: python mlops/6_Regression/4_Analyse/analyse.py --model lightgbm
    deps:
      - mlops/6_Regression/4_Analyse/analyse.py
      - data/encoded/X_test.csv
      - data/encoded/y_test.csv
      - data/encoded/lgbm_model.joblib

  splitst:
    cmd: python mlops/7_Serie_temporelle/1_SPLIT/load_split.py
    deps:
      - mlops/7_Serie_temporelle/1_SPLIT/load_split.py
      - data/df_sales_clean_ST.csv
      - data/processed/contours-codes-postaux.geojson
      - data/clean/taux_immo.xlsx
    outs:
      - data/split

  decompose:
    cmd: python mlops/7_Serie_temporelle/2_Decompose/seasonal_decomp.py --input-folder data/split --output-folder outputs/decomposition --suffix ${ST_SUFFIX}
    deps:
      - mlops/7_Serie_temporelle/2_Decompose/seasonal_decomp.py
      - data/split/train_periodique_q12.csv
    outs:
      - outputs/decomposition/decomposition_additive_cluster_0.png
      - outputs/decomposition/decomposition_multiplicative_cluster_0.png

  train_sarimax:
    cmd: python mlops/7_Serie_temporelle/3_SARIMAX/sarimax_train.py --input-folder data/split --output-folder outputs/best --suffix ${ST_SUFFIX} --corr-threshold 0.25 --top-k-exog 3 --max-exog-comb-size 0 --stop-on-first-valid --max-models 300
    deps:
      - mlops/7_Serie_temporelle/3_SARIMAX/sarimax_train.py
      - data/split/train_periodique_q12.csv
      - data/split/test_periodique_q12.csv
    outs:
      - outputs/best

  evaluate:
    cmd: python mlops/7_Serie_temporelle/4_EVALUATE/evaluate_ST.py --input-folder data/split --model-folder outputs/best --output-folder outputs/evaluate --suffix ${ST_SUFFIX}
    deps:
      - outputs/best
      - data/split
    outs:
      - outputs/evaluate

