dagshub:
  username: "${DAGSHUB_USERNAME}"
  token: "${DAGSHUB_TOKEN}"
  
mlflow:
  tracking_uri: "${DAGSHUB_MLFLOW_TRACKING_URI}"
  tracking_username: "${DAGSHUB_USERNAME}"
  tracking_password: "${DAGSHUB_TOKEN}"
  
dvc:
  remote_url: "${DAGSHUB_DVC_REMOTE_URL}"
  username: "${DAGSHUB_USERNAME}"
  password: "${DAGSHUB_TOKEN}"