FROM python:3.11-slim-bookworm

WORKDIR /app

COPY mlops/5_clustering mlops/5_clustering
COPY data/processed data/processed
COPY exports exports

ENTRYPOINT ["uvicorn", "clustering_api:app", "--host", "0.0.0.0", "--port", "8002"]
