artifact_uri: file:///home/vboxuser/Compagnon_new/Compagnon_immo_25/mlruns/073f01f3387c460c9173ed05ac16e193/artifacts
end_time: 1760745595400
entry_point_name: ''
experiment_id: '590107318283490497'
lifecycle_stage: active
run_id: 073f01f3387c460c9173ed05ac16e193
run_name: Import incrémental [s3]
source_name: ''
source_type: 4
source_version: ''
start_time: 1760745089658
status: 4
tags: []
user_id: vboxuser
