# Dockerfile — build image airflow + pip requirements
FROM apache/airflow:2.9.2

# switch to root to install packages

ENV PYTHONUSERBASE=/home/airflow/.local


# copy requirements file and install dependencies
COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
# restore non-root user (image officielle expose 'airflow' user)
USER airflow

