apiVersion: apps/v1
kind: Deployment
metadata:
  name: compagnon-immo-api
  labels:
    app: compagnon-immo-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: compagnon-immo-api
  template:
    metadata:
      labels:
        app: compagnon-immo-api
    spec:
      containers:
      - name: api
        image: compagnon-immo-api:latest
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: API_HOST
          value: "0.0.0.0"
        - name: API_PORT
          value: "8000"
        - name: WORKERS
          value: "1"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: METRICS_ENABLED
          value: "true"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-url
        - name: MLFLOW_TRACKING_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mlflow-uri
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: compagnon-immo-api-service
  labels:
    app: compagnon-immo-api
spec:
  selector:
    app: compagnon-immo-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
  - name: metrics
    port: 9090
    targetPort: 9090
  type: ClusterIP