FROM compagnon_immo-fus

WORKDIR /app
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*
    
# Étape 3 : copie code
COPY mlops/4_preprocessing /app/mlops/4_preprocessing
COPY data /app/data
COPY mlops /app

EXPOSE 8001 

ENTRYPOINT ["uvicorn", "mlops.4_preprocessing.preprocessing_api:app", "--host", "0.0.0.0", "--port", "8001"]
