FROM compagnon_immo-fus

WORKDIR /app
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*
# Étape 3 : copie code
COPY mlops/preprocessing /app/mlops/preprocessing
COPY data /app/data
COPY services /app
EXPOSE 8001 
ENTRYPOINT ["uvicorn", "preprocessing_api:app", "--host", "0.0.0.0", "--port", "8001"]
