FROM python:3.11-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1
    
# 1. Dépendances système

    
WORKDIR /app

COPY mlops/6_Regression/4_Analyse/requirements.txt /app/mlops/6_Regression/4_Analyse/requirements.txt
COPY mlops/6_Regression/4_Analyse /app/mlops/6_Regression/4_Analyse 
COPY exports /app/exports

RUN pip install --upgrade pip && \
    pip install -r /app/mlops/6_Regression/4_Analyse/requirements.txt
    
ENTRYPOINT ["uvicorn", "analyse_api:app", "--host", "0.0.0.0", "--port", "8005"]
