FROM compagnon_immo-util
WORKDIR /app

COPY mlops/6_Regression/4_Analyse mlops/6_Regression/4_Analyse 
COPY exports /app/exports

ENTRYPOINT ["uvicorn", "analyse_api:app", "--host", "0.0.0.0", "--port", "8005"]
