# --- path: Dockerfile.run
# path: Dockerfile.run
FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# minimal system deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc curl ca-certificates \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# install python deps
RUN pip install --no-cache-dir \
    pandas pyarrow fastparquet \
    boto3 botocore \
    click mlflow \
    duckdb \
    dvc[s3]

# copy project
COPY . /app

# prepare folders
RUN mkdir -p /app/data/state /app/data/incremental /app/output

# default command prints help
CMD ["make", "-f", "Makefile.s3", "help"]
