artifact_location: file:///home/vboxuser/Compagnon_new/Compagnon_immo_25/mlruns
creation_time: 1760738213020
experiment_id: '590107318283490497'
last_update_time: 1760738213020
lifecycle_stage: active
name: Import données
