stages:
  encode:
    cmd: python src/encoding.py
    deps:
      - src/encoding.py
      - mlops/data/df_cluster.csv
    outs:
      - mlops/encoded/X_train.csv
      - mlops/encoded/X_test.csv
      - mlops/encoded/y_train.csv
      - mlops/encoded/y_test.csv

  train_lgbm:
    cmd: python src/train_lgbm.py
    deps:
      - src/train_lgbm.py
      - mlops/encoded/X_train.csv
      - mlops/encoded/y_train.csv
    outs:
      - mlops/encoded/lgbm_model.joblib

  analyse:
    cmd: python src/analyse.py --model lightgbm
    deps:
      - src/analyse.py
      - mlops/encoded/X_test.csv
      - mlops/encoded/y_test.csv
      - mlops/encoded/lgbm_model.joblib

