FROM compagnon_immo-encod
WORKDIR /app


COPY mlops/6_Regression/2_LGBM mlops/6_Regression/2_LGBM
COPY ../../exports /app/exports

ENTRYPOINT ["uvicorn", "train_lgbm_api:app", "--host", "0.0.0.0", "--port", "8004"]

