name: COMPAGNON_SECRET_YAZ

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use PAT to call GitHub API
        run: |
          curl -H "Authorization: token ${{ secrets.COMPAGNON_SECRET_YAZ }}" \
               https://api.github.com/user


