name: permissions
on: { workflow_dispatch: {} }
permissions: { contents: read, actions: write }

defaults: { run: { shell: bash, working-directory: ${{ github.workspace }} } }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Générer .env (POC)
        run: |
          set -euxo pipefail
          echo "HELLO=world" > "$GITHUB_WORKSPACE/.env"
          echo "[debug] wrote: $GITHUB_WORKSPACE/.env"
          pwd; ls -la .; wc -c .env; head -n1 .env

      - name: Upload .env (artefact)
        uses: actions/upload-artifact@v4
        with:
          name: env-artifact
          path: ${{ github.workspace }}/.env
          if-no-files-found: error
          retention-days: 1

