name: permissions
on:
  workflow_dispatch: {}
  push:

permissions:
  contents: read
  actions: write

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  build:
    runs-on: ubuntu-latest


    env:
      COMPAGNON_SECRET_KETSIA: ${{ secrets.COMPAGNON_SECRET_KETSIA }}
      COMPAGNON_SECRET_YAZ:    ${{ secrets.COMPAGNON_SECRET_YAZ }}
      DAGSHUB_USER:            ${{ secrets.DAGSHUB_USERNAME }}
      DAGSHUB_TOKEN:           ${{ secrets.DAGSHUB_TOKEN }}
      DAGSHUB_REPO:            ${{ secrets.DAGSHUB_REPO_NAME }}
      MLFLOW_TRACKING_URI:     ${{ secrets.MLFLOW_TRACKING_URI }}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
      MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Générer config DagsHub/MLflow
        run: make setup_dagshub

      - name: Sanity check MLflow (ping API)
        run: |
          curl -s -u "$MLFLOW_TRACKING_USERNAME:$MLFLOW_TRACKING_PASSWORD" \
            "$MLFLOW_TRACKING_URI/api/2.0/mlflow/experiments/list" | head -n 5

      - name: Afficher config (sans secrets)
        run: cat infra/config/dagshub.yaml

      - name: Générer .env depuis les secrets
        shell: bash
        run: |
          set -eu
          
          echo "AIRFLOW__CORE__FERNET_KEY=${{ secrets.AIRFLOW__CORE__FERNET_KEY }}"
          echo "AIRFLOW__CORE__EXECUTOR=LocalExecutor"
          echo "AIRFLOW__CORE__DEFAULT_TIMEZONE=Europe/Paris"
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
          echo "MLFLOW_BACKEND_STORE_URI=${{ secrets.MLFLOW_BACKEND_STORE_URI }}"
          echo "MLFLOW_ARTIFACT_URI=${{ secrets.MLFLOW_ARTIFACT_URI }}"
          echo "MLFLOW_TRACKING_URI=${{ secrets.MLFLOW_TRACKING_URI }}"
          echo "DAGSHUB_USER=${{ secrets.DAGSHUB_USERNAME }}"
          echo "DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }}"
          echo "DAGSHUB_REPO_OWNER=${{ secrets.DAGSHUB_REPO_OWNER }}"
          echo "DAGSHUB_REPO_NAME=${{ secrets.DAGSHUB_REPO_NAME }}"
          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.MLFLOW_TRACKING_USERNAME }}"
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.MLFLOW_TRACKING_PASSWORD }}"
          echo "[debug] wrote $(pwd)/artifacts/env.txt"
          ls -la .
          ls -la artifacts
          wc -c artifacts/env.txt
          head -n1 artifacts/env.txt

      - name: Upload env artifact
        uses: actions/upload-artifact@v4
        with:
          name: env-artifact
          path: artifacts          # ← on uploade le dossier (non caché)
          if-no-files-found: error
          retention-days: 1

