name: CI - Tests API

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Optionnel: paquets utiles aux tests si absents
          pip install pytest pytest-asyncio requests

      - name: Start API (uvicorn) in background
        env:
          ENVIRONMENT: test
          API_HOST: 0.0.0.0
          API_PORT: 8000
        run: |
          nohup uvicorn app.api.main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 & echo $! > uvicorn.pid

      - name: Wait for API readiness
        run: |
          for i in {1..40}; do
            if curl -sf http://localhost:8000/api/v1/health >/dev/null; then
              echo "API is up"; exit 0
            fi
            sleep 3
          done
          echo "API not ready in time"; echo "--- Uvicorn log ---"; (test -f uvicorn.log && tail -n 200 uvicorn.log) || true; exit 1

      - name: Run tests
        env:
          ENVIRONMENT: test
          API_BASE_URL: http://localhost:8000/api/v1
        run: pytest -q

      - name: Stop API server
        if: always()
        run: |
          if [ -f uvicorn.pid ]; then
            kill $(cat uvicorn.pid) || true
          fi
          (test -f uvicorn.log && tail -n 200 uvicorn.log) || true
