name: trigger-permissions
run: make trigger-permission
env:
  GH_TOKEN: ${{ github.token }}   # requis par la CLI gh en Actions
on:
  workflow_dispatch:        # déclenchable à la demande
  push:
    branches: [ main, Auto_github ]
  pull_request:


