artifact_uri: file:///home/vboxuser/Compagnon_new/Compagnon_immo_25/mlruns/4109342ed50548bfa019ecabccfe89cc/artifacts
end_time: 1760747907130
entry_point_name: ''
experiment_id: '590107318283490497'
lifecycle_stage: active
run_id: 4109342ed50548bfa019ecabccfe89cc
run_name: Import incrémental [s3]
source_name: ''
source_type: 4
source_version: ''
start_time: 1760747476398
status: 4
tags: []
user_id: vboxuser
