FROM compagnon_immo-fus

WORKDIR /app
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH=/app

    
# Étape 3 : copie code
COPY mlops/preprocessing_4 /app/mlops/preprocessing_4
COPY data /app/data
COPY mlops /app


USER root
RUN chown -R 1000:1000 /app

# Puis exécute avec un utilisateur non root
USER 1000


EXPOSE 8001 

ENTRYPOINT ["uvicorn", "mlops.preprocessing_4.preprocessing_api:app", "--host", "0.0.0.0", "--port", "8001"]
